package com.amorim.finance_manager.shared.exception;

public enum ApiErrorCode {

    VALIDATION_ERROR,
    INVALID_REQUEST,

    INVALID_CREDENTIALS,
    UNAUTHORIZED,
    RATE_LIMIT_EXCEEDED,
    CSRF_VALIDATION_FAILED,

    ACCOUNT_NOT_FOUND,
    CATEGORY_NOT_FOUND,
    TRANSACTION_NOT_FOUND,
    RESOURCE_NOT_FOUND,
    CREDIT_CARD_NOT_FOUND,
    INVOICE_NOT_FOUND,
    BUDGET_NOT_FOUND,

    EMAIL_ALREADY_EXISTS,
    BUDGET_ALREADY_EXISTS,

    INVALID_PROFILE_UPDATE,
    INVALID_PASSWORD_CHANGE,
    INVALID_ACCOUNT_UPDATE,
    INVALID_CREDIT_CARD_UPDATE,
    INVALID_CATEGORY_UPDATE,
    INVALID_BUDGET_UPDATE,

    INACTIVE_ACCOUNT,
    CATEGORY_TYPE_MISMATCH,

    INVALID_BALANCE_AMOUNT,
    INVALID_TRANSACTION,
    INVALID_TRANSFER,

    INVALID_TRANSACTION_STATUS,
    INVALID_CREDIT_CARD_STATUS,
    INVALID_INVOICE_STATUS,

    OPTIMISTIC_LOCK_CONFLICT,
    CREDIT_LIMIT_CONFLICT,

    METHOD_NOT_ALLOWED,
    UNSUPPORTED_MEDIA_TYPE,
    INTERNAL_SERVER_ERROR,

    TRANSACTION_ALREADY_CANCELLED,

    INVALID_REPORT_PERIOD,

    INVALID_CREDIT_CARD_REFUND,
    CREDIT_CARD_PURCHASE_ALREADY_REFUNDED,

    INVALID_INVOICE_PAYMENT,
}
